<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CFS-LP-0219" failures="1" tests="4" name="UI Automation" time="19.872" errors="0" timestamp="2025-10-05T19:32:18 IST">
  <testcase classname="com.ui.tests.LoginTest" name="loginTest" time="5.329"/>
  <testcase classname="com.ui.tests.LogoutTest" name="logout" time="8.895"/>
  <testcase classname="com.ui.tests.SupportTest" name="supportCreation" time="11.65"/>
  <testcase classname="com.ui.tests.MachineTest" name="machineTest" time="14.211">
    <failure type="java.lang.AssertionError" message="expected [Request confirmed] but found [Aanvraag bevestigd!]">
      <![CDATA[java.lang.AssertionError: expected [Request confirmed] but found [Aanvraag bevestigd!]
at com.ui.tests.MachineTest.machineTest(MachineTest.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- machineTest -->
</testsuite> <!-- UI Automation -->
